package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Adjudicacion generated by hbm2java
 */
@Entity
@Table(name = "adjudicacion", catalog = "marketplace")
public class Adjudicacion implements java.io.Serializable {

	private Long idAdjudicacion;
	private OfertaCotizacion ofertaCotizacion;
	private Cotizacion cotizacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String comentarios;

	public Adjudicacion() {
	}

	public Adjudicacion(OfertaCotizacion ofertaCotizacion,
			Cotizacion cotizacion, Date fechaCreacion, Date fechaModificacion) {
		this.ofertaCotizacion = ofertaCotizacion;
		this.cotizacion = cotizacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
	}

	public Adjudicacion(OfertaCotizacion ofertaCotizacion,
			Cotizacion cotizacion, Date fechaCreacion, Date fechaModificacion,
			String comentarios) {
		this.ofertaCotizacion = ofertaCotizacion;
		this.cotizacion = cotizacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.comentarios = comentarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_adjudicacion", unique = true, nullable = false)
	public Long getIdAdjudicacion() {
		return this.idAdjudicacion;
	}

	public void setIdAdjudicacion(Long idAdjudicacion) {
		this.idAdjudicacion = idAdjudicacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_oferta_cotizacion", nullable = false)
	public OfertaCotizacion getOfertaCotizacion() {
		return this.ofertaCotizacion;
	}

	public void setOfertaCotizacion(OfertaCotizacion ofertaCotizacion) {
		this.ofertaCotizacion = ofertaCotizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cotizacion", nullable = false)
	public Cotizacion getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(Cotizacion cotizacion) {
		this.cotizacion = cotizacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "comentarios", length = 65535)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

}
