package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Combustible generated by hbm2java
 */
@Entity
@Table(name = "combustible", catalog = "marketplace")
public class Combustible implements java.io.Serializable {

	private short idCombustible;
	private String descripcion;
	private Set proveedorSucursals = new HashSet(0);
	private Set vehiculos = new HashSet(0);

	public Combustible() {
	}

	public Combustible(short idCombustible, String descripcion) {
		this.idCombustible = idCombustible;
		this.descripcion = descripcion;
	}

	public Combustible(short idCombustible, String descripcion,
			Set proveedorSucursals, Set vehiculos) {
		this.idCombustible = idCombustible;
		this.descripcion = descripcion;
		this.proveedorSucursals = proveedorSucursals;
		this.vehiculos = vehiculos;
	}

	@Id
	@Column(name = "id_combustible", unique = true, nullable = false)
	public short getIdCombustible() {
		return this.idCombustible;
	}

	public void setIdCombustible(short idCombustible) {
		this.idCombustible = idCombustible;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "combustible")
	public Set getProveedorSucursals() {
		return this.proveedorSucursals;
	}

	public void setProveedorSucursals(Set proveedorSucursals) {
		this.proveedorSucursals = proveedorSucursals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "combustible")
	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
