package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EstadoProveedor generated by hbm2java
 */
@Entity
@Table(name = "estado_proveedor", catalog = "marketplace")
public class EstadoProveedor implements java.io.Serializable {

	private short idEstadoProveedor;
	private String descripcion;
	private Set proveedors = new HashSet(0);

	public EstadoProveedor() {
	}

	public EstadoProveedor(short idEstadoProveedor, String descripcion) {
		this.idEstadoProveedor = idEstadoProveedor;
		this.descripcion = descripcion;
	}

	public EstadoProveedor(short idEstadoProveedor, String descripcion,
			Set proveedors) {
		this.idEstadoProveedor = idEstadoProveedor;
		this.descripcion = descripcion;
		this.proveedors = proveedors;
	}

	@Id
	@Column(name = "id_estado_proveedor", unique = true, nullable = false)
	public short getIdEstadoProveedor() {
		return this.idEstadoProveedor;
	}

	public void setIdEstadoProveedor(short idEstadoProveedor) {
		this.idEstadoProveedor = idEstadoProveedor;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadoProveedor")
	public Set getProveedors() {
		return this.proveedors;
	}

	public void setProveedors(Set proveedors) {
		this.proveedors = proveedors;
	}

}
