package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Marca generated by hbm2java
 */
@Entity
@Table(name = "marca", catalog = "marketplace")
public class Marca implements java.io.Serializable {

	private int idMarca;
	private TipoVehiculo tipoVehiculo;
	private String descripcion;
	private Set modelos = new HashSet(0);
	private Set marcaProveedors = new HashSet(0);

	public Marca() {
	}

	public Marca(int idMarca, TipoVehiculo tipoVehiculo, String descripcion) {
		this.idMarca = idMarca;
		this.tipoVehiculo = tipoVehiculo;
		this.descripcion = descripcion;
	}

	public Marca(int idMarca, TipoVehiculo tipoVehiculo, String descripcion,
			Set modelos, Set marcaProveedors) {
		this.idMarca = idMarca;
		this.tipoVehiculo = tipoVehiculo;
		this.descripcion = descripcion;
		this.modelos = modelos;
		this.marcaProveedors = marcaProveedors;
	}

	@Id
	@Column(name = "id_marca", unique = true, nullable = false)
	public int getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(int idMarca) {
		this.idMarca = idMarca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_vehiculo", nullable = false)
	public TipoVehiculo getTipoVehiculo() {
		return this.tipoVehiculo;
	}

	public void setTipoVehiculo(TipoVehiculo tipoVehiculo) {
		this.tipoVehiculo = tipoVehiculo;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set getModelos() {
		return this.modelos;
	}

	public void setModelos(Set modelos) {
		this.modelos = modelos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set getMarcaProveedors() {
		return this.marcaProveedors;
	}

	public void setMarcaProveedors(Set marcaProveedors) {
		this.marcaProveedors = marcaProveedors;
	}

}
