package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MedioPago generated by hbm2java
 */
@Entity
@Table(name = "medio_pago", catalog = "marketplace")
public class MedioPago implements java.io.Serializable {

	private short idMedioPago;
	private String descripcion;
	private Set facturas = new HashSet(0);

	public MedioPago() {
	}

	public MedioPago(short idMedioPago, String descripcion) {
		this.idMedioPago = idMedioPago;
		this.descripcion = descripcion;
	}

	public MedioPago(short idMedioPago, String descripcion, Set facturas) {
		this.idMedioPago = idMedioPago;
		this.descripcion = descripcion;
		this.facturas = facturas;
	}

	@Id
	@Column(name = "id_medio_pago", unique = true, nullable = false)
	public short getIdMedioPago() {
		return this.idMedioPago;
	}

	public void setIdMedioPago(short idMedioPago) {
		this.idMedioPago = idMedioPago;
	}

	@Column(name = "descripcion", nullable = false, length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "medioPago")
	public Set getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set facturas) {
		this.facturas = facturas;
	}

}
