package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "marketplace")
public class Modelo implements java.io.Serializable {

	private int idModelo;
	private Marca marca;
	private String descripcion;
	private Set vehiculos = new HashSet(0);

	public Modelo() {
	}

	public Modelo(int idModelo, Marca marca, String descripcion) {
		this.idModelo = idModelo;
		this.marca = marca;
		this.descripcion = descripcion;
	}

	public Modelo(int idModelo, Marca marca, String descripcion, Set vehiculos) {
		this.idModelo = idModelo;
		this.marca = marca;
		this.descripcion = descripcion;
		this.vehiculos = vehiculos;
	}

	@Id
	@Column(name = "id_modelo", unique = true, nullable = false)
	public int getIdModelo() {
		return this.idModelo;
	}

	public void setIdModelo(int idModelo) {
		this.idModelo = idModelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_marca", nullable = false)
	public Marca getMarca() {
		return this.marca;
	}

	public void setMarca(Marca marca) {
		this.marca = marca;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
