package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OfertaCotizacion generated by hbm2java
 */
@Entity
@Table(name = "oferta_cotizacion", catalog = "marketplace")
public class OfertaCotizacion implements java.io.Serializable {

	private Long idOfertaCotizacion;
	private ProveedorSucursal proveedorSucursal;
	private Cotizacion cotizacion;
	private Date fechaCreacion;
	private Date fechaModificacion;
	private String comentarios;
	private Set adjudicacions = new HashSet(0);

	public OfertaCotizacion() {
	}

	public OfertaCotizacion(ProveedorSucursal proveedorSucursal,
			Cotizacion cotizacion, Date fechaCreacion, Date fechaModificacion) {
		this.proveedorSucursal = proveedorSucursal;
		this.cotizacion = cotizacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
	}

	public OfertaCotizacion(ProveedorSucursal proveedorSucursal,
			Cotizacion cotizacion, Date fechaCreacion, Date fechaModificacion,
			String comentarios, Set adjudicacions) {
		this.proveedorSucursal = proveedorSucursal;
		this.cotizacion = cotizacion;
		this.fechaCreacion = fechaCreacion;
		this.fechaModificacion = fechaModificacion;
		this.comentarios = comentarios;
		this.adjudicacions = adjudicacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_oferta_cotizacion", unique = true, nullable = false)
	public Long getIdOfertaCotizacion() {
		return this.idOfertaCotizacion;
	}

	public void setIdOfertaCotizacion(Long idOfertaCotizacion) {
		this.idOfertaCotizacion = idOfertaCotizacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proveedor_sucursal", nullable = false)
	public ProveedorSucursal getProveedorSucursal() {
		return this.proveedorSucursal;
	}

	public void setProveedorSucursal(ProveedorSucursal proveedorSucursal) {
		this.proveedorSucursal = proveedorSucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cotizacion", nullable = false)
	public Cotizacion getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(Cotizacion cotizacion) {
		this.cotizacion = cotizacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_creacion", nullable = false, length = 19)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha_modificacion", nullable = false, length = 19)
	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	@Column(name = "comentarios", length = 65535)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ofertaCotizacion")
	public Set getAdjudicacions() {
		return this.adjudicacions;
	}

	public void setAdjudicacions(Set adjudicacions) {
		this.adjudicacions = adjudicacions;
	}

}
