package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "marketplace")
public class Pais implements java.io.Serializable {

	private int idPais;
	private String descripcion;
	private Set regions = new HashSet(0);

	public Pais() {
	}

	public Pais(int idPais, String descripcion) {
		this.idPais = idPais;
		this.descripcion = descripcion;
	}

	public Pais(int idPais, String descripcion, Set regions) {
		this.idPais = idPais;
		this.descripcion = descripcion;
		this.regions = regions;
	}

	@Id
	@Column(name = "id_pais", unique = true, nullable = false)
	public int getIdPais() {
		return this.idPais;
	}

	public void setIdPais(int idPais) {
		this.idPais = idPais;
	}

	@Column(name = "descripcion", nullable = false, length = 128)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set getRegions() {
		return this.regions;
	}

	public void setRegions(Set regions) {
		this.regions = regions;
	}

}
