package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProveedorSucursalUsuario generated by hbm2java
 */
@Entity
@Table(name = "proveedor_sucursal_usuario", catalog = "marketplace")
public class ProveedorSucursalUsuario implements java.io.Serializable {

	private Integer idProveedorSucursalUsuario;
	private ProveedorSucursal proveedorSucursal;
	private Rol rol;
	private Usuario usuario;
	private String rut;
	private String correo;
	private String telefono;

	public ProveedorSucursalUsuario() {
	}

	public ProveedorSucursalUsuario(ProveedorSucursal proveedorSucursal,
			Rol rol, Usuario usuario) {
		this.proveedorSucursal = proveedorSucursal;
		this.rol = rol;
		this.usuario = usuario;
	}

	public ProveedorSucursalUsuario(ProveedorSucursal proveedorSucursal,
			Rol rol, Usuario usuario, String rut, String correo, String telefono) {
		this.proveedorSucursal = proveedorSucursal;
		this.rol = rol;
		this.usuario = usuario;
		this.rut = rut;
		this.correo = correo;
		this.telefono = telefono;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_proveedor_sucursal_usuario", unique = true, nullable = false)
	public Integer getIdProveedorSucursalUsuario() {
		return this.idProveedorSucursalUsuario;
	}

	public void setIdProveedorSucursalUsuario(Integer idProveedorSucursalUsuario) {
		this.idProveedorSucursalUsuario = idProveedorSucursalUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proveedor_sucursal", nullable = false)
	public ProveedorSucursal getProveedorSucursal() {
		return this.proveedorSucursal;
	}

	public void setProveedorSucursal(ProveedorSucursal proveedorSucursal) {
		this.proveedorSucursal = proveedorSucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rol", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "rut", length = 15)
	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	@Column(name = "correo", length = 45)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
