package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProveedorSucursalServicio generated by hbm2java
 */
@Entity
@Table(name = "proveedor_sucursal_servicio", catalog = "marketplace")
public class ProveedorSucursalServicio implements java.io.Serializable {

	private Long idProveedorSucursalServicio;
	private ProveedorSucursal proveedorSucursal;
	private Servicio servicio;
	private TipoVehiculo tipoVehiculo;

	public ProveedorSucursalServicio() {
	}

	public ProveedorSucursalServicio(ProveedorSucursal proveedorSucursal,
			Servicio servicio, TipoVehiculo tipoVehiculo) {
		this.proveedorSucursal = proveedorSucursal;
		this.servicio = servicio;
		this.tipoVehiculo = tipoVehiculo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_proveedor_sucursal_servicio", unique = true, nullable = false)
	public Long getIdProveedorSucursalServicio() {
		return this.idProveedorSucursalServicio;
	}

	public void setIdProveedorSucursalServicio(Long idProveedorSucursalServicio) {
		this.idProveedorSucursalServicio = idProveedorSucursalServicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_proveedor_sucursal", nullable = false)
	public ProveedorSucursal getProveedorSucursal() {
		return this.proveedorSucursal;
	}

	public void setProveedorSucursal(ProveedorSucursal proveedorSucursal) {
		this.proveedorSucursal = proveedorSucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_servicio", nullable = false)
	public Servicio getServicio() {
		return this.servicio;
	}

	public void setServicio(Servicio servicio) {
		this.servicio = servicio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_vehiculo", nullable = false)
	public TipoVehiculo getTipoVehiculo() {
		return this.tipoVehiculo;
	}

	public void setTipoVehiculo(TipoVehiculo tipoVehiculo) {
		this.tipoVehiculo = tipoVehiculo;
	}

}
