package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Region generated by hbm2java
 */
@Entity
@Table(name = "region", catalog = "marketplace")
public class Region implements java.io.Serializable {

	private int idRegion;
	private Pais pais;
	private String descripcion;
	private Set comunas = new HashSet(0);

	public Region() {
	}

	public Region(int idRegion, Pais pais, String descripcion) {
		this.idRegion = idRegion;
		this.pais = pais;
		this.descripcion = descripcion;
	}

	public Region(int idRegion, Pais pais, String descripcion, Set comunas) {
		this.idRegion = idRegion;
		this.pais = pais;
		this.descripcion = descripcion;
		this.comunas = comunas;
	}

	@Id
	@Column(name = "id_region", unique = true, nullable = false)
	public int getIdRegion() {
		return this.idRegion;
	}

	public void setIdRegion(int idRegion) {
		this.idRegion = idRegion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pais", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "descripcion", nullable = false, length = 128)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "region")
	public Set getComunas() {
		return this.comunas;
	}

	public void setComunas(Set comunas) {
		this.comunas = comunas;
	}

}
