package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol", catalog = "marketplace")
public class Rol implements java.io.Serializable {

	private short idRol;
	private String descripcion;
	private Set proveedorSucursalUsuarios = new HashSet(0);

	public Rol() {
	}

	public Rol(short idRol, String descripcion) {
		this.idRol = idRol;
		this.descripcion = descripcion;
	}

	public Rol(short idRol, String descripcion, Set proveedorSucursalUsuarios) {
		this.idRol = idRol;
		this.descripcion = descripcion;
		this.proveedorSucursalUsuarios = proveedorSucursalUsuarios;
	}

	@Id
	@Column(name = "id_rol", unique = true, nullable = false)
	public short getIdRol() {
		return this.idRol;
	}

	public void setIdRol(short idRol) {
		this.idRol = idRol;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set getProveedorSucursalUsuarios() {
		return this.proveedorSucursalUsuarios;
	}

	public void setProveedorSucursalUsuarios(Set proveedorSucursalUsuarios) {
		this.proveedorSucursalUsuarios = proveedorSucursalUsuarios;
	}

}
