package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoVehiculo generated by hbm2java
 */
@Entity
@Table(name = "tipo_vehiculo", catalog = "marketplace")
public class TipoVehiculo implements java.io.Serializable {

	private short idTipoVehiculo;
	private String descripcion;
	private Set proveedorSucursalServicios = new HashSet(0);
	private Set marcas = new HashSet(0);

	public TipoVehiculo() {
	}

	public TipoVehiculo(short idTipoVehiculo, String descripcion) {
		this.idTipoVehiculo = idTipoVehiculo;
		this.descripcion = descripcion;
	}

	public TipoVehiculo(short idTipoVehiculo, String descripcion,
			Set proveedorSucursalServicios, Set marcas) {
		this.idTipoVehiculo = idTipoVehiculo;
		this.descripcion = descripcion;
		this.proveedorSucursalServicios = proveedorSucursalServicios;
		this.marcas = marcas;
	}

	@Id
	@Column(name = "id_tipo_vehiculo", unique = true, nullable = false)
	public short getIdTipoVehiculo() {
		return this.idTipoVehiculo;
	}

	public void setIdTipoVehiculo(short idTipoVehiculo) {
		this.idTipoVehiculo = idTipoVehiculo;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVehiculo")
	public Set getProveedorSucursalServicios() {
		return this.proveedorSucursalServicios;
	}

	public void setProveedorSucursalServicios(Set proveedorSucursalServicios) {
		this.proveedorSucursalServicios = proveedorSucursalServicios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVehiculo")
	public Set getMarcas() {
		return this.marcas;
	}

	public void setMarcas(Set marcas) {
		this.marcas = marcas;
	}

}
