package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoTransmision generated by hbm2java
 */
@Entity
@Table(name = "tipo_transmision", catalog = "marketplace")
public class TipoTransmision implements java.io.Serializable {

	private short idTipoTransmision;
	private String descripcion;
	private Set vehiculos = new HashSet(0);

	public TipoTransmision() {
	}

	public TipoTransmision(short idTipoTransmision, String descripcion) {
		this.idTipoTransmision = idTipoTransmision;
		this.descripcion = descripcion;
	}

	public TipoTransmision(short idTipoTransmision, String descripcion,
			Set vehiculos) {
		this.idTipoTransmision = idTipoTransmision;
		this.descripcion = descripcion;
		this.vehiculos = vehiculos;
	}

	@Id
	@Column(name = "id_tipo_transmision", unique = true, nullable = false)
	public short getIdTipoTransmision() {
		return this.idTipoTransmision;
	}

	public void setIdTipoTransmision(short idTipoTransmision) {
		this.idTipoTransmision = idTipoTransmision;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoTransmision")
	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
