package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Traccion generated by hbm2java
 */
@Entity
@Table(name = "traccion", catalog = "marketplace")
public class Traccion implements java.io.Serializable {

	private short idTraccion;
	private String descripcion;
	private Set vehiculos = new HashSet(0);

	public Traccion() {
	}

	public Traccion(short idTraccion, String descripcion) {
		this.idTraccion = idTraccion;
		this.descripcion = descripcion;
	}

	public Traccion(short idTraccion, String descripcion, Set vehiculos) {
		this.idTraccion = idTraccion;
		this.descripcion = descripcion;
		this.vehiculos = vehiculos;
	}

	@Id
	@Column(name = "id_traccion", unique = true, nullable = false)
	public short getIdTraccion() {
		return this.idTraccion;
	}

	public void setIdTraccion(short idTraccion) {
		this.idTraccion = idTraccion;
	}

	@Column(name = "descripcion", nullable = false, length = 32)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "traccion")
	public Set getVehiculos() {
		return this.vehiculos;
	}

	public void setVehiculos(Set vehiculos) {
		this.vehiculos = vehiculos;
	}

}
