package cl.dsoft.car.marketplace.domain;

// Generated Feb 28, 2016 2:15:19 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Vehiculo generated by hbm2java
 */
@Entity
@Table(name = "vehiculo", catalog = "marketplace")
public class Vehiculo implements java.io.Serializable {

	private Long idVehiculo;
	private Traccion traccion;
	private Combustible combustible;
	private Modelo modelo;
	private Usuario usuario;
	private TipoTransmision tipoTransmision;
	private String patente;
	private Short anio;
	private Boolean aireAcondicionado;
	private Boolean alzaVidrios;
	private Set cotizacions = new HashSet(0);

	public Vehiculo() {
	}

	public Vehiculo(Traccion traccion, Combustible combustible, Modelo modelo,
			Usuario usuario, TipoTransmision tipoTransmision) {
		this.traccion = traccion;
		this.combustible = combustible;
		this.modelo = modelo;
		this.usuario = usuario;
		this.tipoTransmision = tipoTransmision;
	}

	public Vehiculo(Traccion traccion, Combustible combustible, Modelo modelo,
			Usuario usuario, TipoTransmision tipoTransmision, String patente,
			Short anio, Boolean aireAcondicionado, Boolean alzaVidrios,
			Set cotizacions) {
		this.traccion = traccion;
		this.combustible = combustible;
		this.modelo = modelo;
		this.usuario = usuario;
		this.tipoTransmision = tipoTransmision;
		this.patente = patente;
		this.anio = anio;
		this.aireAcondicionado = aireAcondicionado;
		this.alzaVidrios = alzaVidrios;
		this.cotizacions = cotizacions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_vehiculo", unique = true, nullable = false)
	public Long getIdVehiculo() {
		return this.idVehiculo;
	}

	public void setIdVehiculo(Long idVehiculo) {
		this.idVehiculo = idVehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_traccion", nullable = false)
	public Traccion getTraccion() {
		return this.traccion;
	}

	public void setTraccion(Traccion traccion) {
		this.traccion = traccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_combustible", nullable = false)
	public Combustible getCombustible() {
		return this.combustible;
	}

	public void setCombustible(Combustible combustible) {
		this.combustible = combustible;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_modelo", nullable = false)
	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_transmision", nullable = false)
	public TipoTransmision getTipoTransmision() {
		return this.tipoTransmision;
	}

	public void setTipoTransmision(TipoTransmision tipoTransmision) {
		this.tipoTransmision = tipoTransmision;
	}

	@Column(name = "patente", length = 8)
	public String getPatente() {
		return this.patente;
	}

	public void setPatente(String patente) {
		this.patente = patente;
	}

	@Column(name = "anio")
	public Short getAnio() {
		return this.anio;
	}

	public void setAnio(Short anio) {
		this.anio = anio;
	}

	@Column(name = "aire_acondicionado")
	public Boolean getAireAcondicionado() {
		return this.aireAcondicionado;
	}

	public void setAireAcondicionado(Boolean aireAcondicionado) {
		this.aireAcondicionado = aireAcondicionado;
	}

	@Column(name = "alza_vidrios")
	public Boolean getAlzaVidrios() {
		return this.alzaVidrios;
	}

	public void setAlzaVidrios(Boolean alzaVidrios) {
		this.alzaVidrios = alzaVidrios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vehiculo")
	public Set getCotizacions() {
		return this.cotizacions;
	}

	public void setCotizacions(Set cotizacions) {
		this.cotizacions = cotizacions;
	}

}
